#!/bin/sh
# make sure we don't get the id 0
notify-send -t 1 "a"

id=0
while true; do
    if [ -f /tmp/clockd.run ]; then
	    id=$(notify-send -t 0 -p -r $id "$(date)")
    else
	    if [ $id -ne 0 ]; then
            notify-send -t 10 -r $id "placeholder"
	        id=0
	    fi
    fi
    sleep 1
done
