#!/bin/sh
id=-1
while true; do
    if [ -f /tmp/clockd.run ]; then
	if [ $id -eq -1 ]; then
	    id=$(notify-send -p "placeholder")
	fi
        notify-send -r $id "$(date)"
    else
	if [ $id -ne -1 ]; then
	    notify-send -r $id -t 10 placeholder
	    id=-1
	fi
    fi
    sleep 1
done
